const aiTools = [
    // Pre-existing mock data
    {
        id: "chatgpt",
        name: "ChatGPT",
        company: "OpenAI",
        description: "Modelo de linguagem avançado para conversação, geração de textos e análise de dados.",
        categories: ["Texto", "Código", "Geração de Conteúdo", "Idiomas"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://chatgpt.com",
        icon: "",
        iconFallback: "C",
        themeColor: "bg-green-600"
    },
    {
        id: "gemini",
        name: "Gemini",
        company: "Google",
        description: "Modelo multimodal do Google capaz de raciocinar sobre texto, imagens, vídeo e código.",
        categories: ["Texto", "Imagens", "Código", "Vídeo", "Geração de Conteúdo"],
        pricing: ["Plano Gratuito", "Uso por Plano", "Uso por API"],
        url: "https://gemini.google.com",
        icon: "",
        iconFallback: "G",
        themeColor: "bg-blue-500"
    },
    {
        id: "midjourney",
        name: "Midjourney",
        company: "Midjourney Inc.",
        description: "Geração de imagens de alta qualidade a partir de descrições em linguagem natural.",
        categories: ["Imagens", "Criação Visual"],
        pricing: ["Uso por Plano"],
        url: "https://midjourney.com",
        icon: "",
        iconFallback: "M",
        themeColor: "bg-slate-700"
    },
    {
        id: "claude",
        name: "Claude",
        company: "Anthropic",
        description: "Assistente de IA focado em segurança, com janelas de contexto extremamente longas.",
        categories: ["Texto", "Código", "Geração de Conteúdo", "Pesquisa"],
        pricing: ["Plano Gratuito", "Uso por Plano", "Uso por API"],
        url: "https://claude.ai",
        icon: "",
        iconFallback: "C",
        themeColor: "bg-orange-800"
    },
    {
        id: "suno",
        name: "Suno",
        company: "Suno AI",
        description: "Plataforma de criação musical impulsionada por IA que gera músicas completas com vocais.",
        categories: ["Áudio", "Músicas"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://suno.com",
        icon: "",
        iconFallback: "S",
        themeColor: "bg-pink-600"
    },
    // New tools from study
    {
        id: "khanmigo",
        name: "Khanmigo",
        company: "Khan Academy",
        description: "Atua como tutor personalizado, ajudando alunos a resolver problemas de matemática e ciências com explicações.",
        categories: ["Tutoria", "Educação"],
        pricing: ["Uso por Plano"],
        url: "https://khanmigo.ai",
        icon: "",
        iconFallback: "K",
        themeColor: "bg-green-500"
    },
    {
        id: "magicschool",
        name: "MagicSchool",
        company: "MagicSchool",
        description: "Tutor personalizado e suporte a professores.",
        categories: ["Tutoria", "Educação"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://www.magicschool.ai",
        icon: "",
        iconFallback: "M",
        themeColor: "bg-purple-500"
    },
    {
        id: "quillbot",
        name: "QuillBot",
        company: "QuillBot",
        description: "Auxilia na escrita acadêmica, estruturação de anotações e reescrita de textos.",
        categories: ["Texto", "Redação"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://quillbot.com",
        icon: "",
        iconFallback: "Q",
        themeColor: "bg-green-700"
    },
    {
        id: "elicit",
        name: "Elicit",
        company: "Elicit",
        description: "Assistente de pesquisa baseado em IA para análise de artigos e literatura científica.",
        categories: ["Pesquisa", "Redação"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://elicit.com",
        icon: "",
        iconFallback: "E",
        themeColor: "bg-indigo-600"
    },
    {
        id: "canva",
        name: "Canva / Magic Studio",
        company: "Canva",
        description: "Plataforma de design com suporte a IA para geração de imagens, vídeos e slides.",
        categories: ["Imagens", "Criação Visual", "Vídeo"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://canva.com",
        icon: "",
        iconFallback: "C",
        themeColor: "bg-blue-400"
    },
    {
        id: "copilot",
        name: "Microsoft Copilot",
        company: "Microsoft",
        description: "Assistente de IA integrado ao ecossistema Microsoft para geração de conteúdo e código.",
        categories: ["Texto", "Código", "Geração de Conteúdo"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://copilot.microsoft.com",
        icon: "",
        iconFallback: "C",
        themeColor: "bg-blue-600"
    },
    {
        id: "notionai",
        name: "Notion AI",
        company: "Notion",
        description: "Integração de IA para organizar anotações, gerar ideias e redigir textos.",
        categories: ["Texto", "Produtividade"],
        pricing: ["Uso por Plano"],
        url: "https://notion.so",
        icon: "",
        iconFallback: "N",
        themeColor: "bg-slate-800"
    },
    {
        id: "perplexity",
        name: "Perplexity AI",
        company: "Perplexity AI",
        description: "Motor de busca conversacional que agiliza pesquisa e fornece respostas baseadas em fontes da web.",
        categories: ["Pesquisa", "Texto"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://perplexity.ai",
        icon: "",
        iconFallback: "P",
        themeColor: "bg-slate-900"
    },
    {
        id: "jasper",
        name: "Jasper AI",
        company: "Jasper AI",
        description: "Assistente de redação e criação visual voltado para marketing e negócios.",
        categories: ["Texto", "Criação Visual"],
        pricing: ["Uso por Plano"],
        url: "https://jasper.ai",
        icon: "",
        iconFallback: "J",
        themeColor: "bg-indigo-500"
    },
    {
        id: "gamma",
        name: "Gamma App",
        company: "Gamma",
        description: "Criação visual de apresentações e documentos interativos com ajuda de IA.",
        categories: ["Criação Visual", "Produtividade"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://gamma.app",
        icon: "",
        iconFallback: "G",
        themeColor: "bg-pink-500"
    },
    {
        id: "questionwell",
        name: "QuestionWell",
        company: "QuestionWell",
        description: "Geração de exercícios e perguntas a partir de textos base.",
        categories: ["Educação"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://questionwell.org",
        icon: "",
        iconFallback: "Q",
        themeColor: "bg-yellow-600"
    },
    {
        id: "kahoot",
        name: "Kahoot AI",
        company: "Kahoot",
        description: "Criação de quizzes interativos com auxílio de IA.",
        categories: ["Educação"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://kahoot.com",
        icon: "",
        iconFallback: "K",
        themeColor: "bg-purple-600"
    },
    {
        id: "quizlet",
        name: "Quizlet AI",
        company: "Quizlet",
        description: "Flashcards e avaliações gerados por IA para apoiar estudos.",
        categories: ["Educação"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://quizlet.com",
        icon: "",
        iconFallback: "Q",
        themeColor: "bg-blue-500"
    },
    {
        id: "edpuzzle",
        name: "Edpuzzle AI",
        company: "Edpuzzle",
        description: "Criação de perguntas interativas em vídeos educacionais.",
        categories: ["Educação", "Vídeo"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://edpuzzle.com",
        icon: "",
        iconFallback: "E",
        themeColor: "bg-yellow-500"
    },
    {
        id: "explainpaper",
        name: "ExplainPaper",
        company: "ExplainPaper",
        description: "Auxilia estudantes a entender papers complexos explicando trechos selecionados.",
        categories: ["Pesquisa", "Educação"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://explainpaper.com",
        icon: "",
        iconFallback: "E",
        themeColor: "bg-slate-700"
    },
    {
        id: "tutorai",
        name: "TutorAI",
        company: "TutorAI",
        description: "Plataforma que cria pequenos cursos e explicações sobre qualquer tópico.",
        categories: ["Educação", "Tutoria"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://tutorai.me",
        icon: "",
        iconFallback: "T",
        themeColor: "bg-green-600"
    },
    {
        id: "notebooklm",
        name: "NotebookLM",
        company: "Google",
        description: "Organiza notas e documentos, permitindo fazer perguntas diretamente aos seus arquivos.",
        categories: ["Pesquisa", "Produtividade"],
        pricing: ["Uso Gratuito"],
        url: "https://notebooklm.google.com",
        icon: "",
        iconFallback: "N",
        themeColor: "bg-blue-600"
    },
    {
        id: "teachy",
        name: "Teachy",
        company: "Teachy",
        description: "Suporte ao professor no planejamento e condução de aulas.",
        categories: ["Educação"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://teachy.com.br",
        icon: "",
        iconFallback: "T",
        themeColor: "bg-teal-500"
    },
    {
        id: "curipod",
        name: "Curipod",
        company: "Curipod",
        description: "Apresentações interativas e lições geradas por IA.",
        categories: ["Educação", "Criação Visual"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://curipod.com",
        icon: "",
        iconFallback: "C",
        themeColor: "bg-pink-500"
    },
    {
        id: "schoolai",
        name: "SchoolAI",
        company: "SchoolAI",
        description: "Assistente focado em K-12 para professores economizarem tempo em tarefas.",
        categories: ["Educação", "Gestão Escolar"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://schoolai.com",
        icon: "",
        iconFallback: "S",
        themeColor: "bg-indigo-500"
    },
    {
        id: "diffit",
        name: "Diffit",
        company: "Diffit",
        description: "Adapta textos para diferentes níveis de leitura instantaneamente.",
        categories: ["Educação", "Texto"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://web.diffit.me",
        icon: "",
        iconFallback: "D",
        themeColor: "bg-blue-400"
    },
    {
        id: "scholarai",
        name: "ScholarAI",
        company: "ScholarAI",
        description: "Buscas acadêmicas focadas em artigos revisados por pares.",
        categories: ["Pesquisa"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://scholarai.io",
        icon: "",
        iconFallback: "S",
        themeColor: "bg-emerald-600"
    },
    {
        id: "researchrabbit",
        name: "Research Rabbit",
        company: "Research Rabbit",
        description: "Mapeamento visual e descoberta de citações e artigos relacionados.",
        categories: ["Pesquisa"],
        pricing: ["Uso Gratuito"],
        url: "https://researchrabbit.ai",
        icon: "",
        iconFallback: "R",
        themeColor: "bg-red-500"
    },
    {
        id: "litmaps",
        name: "Litmaps",
        company: "Litmaps",
        description: "Gera mapas de literatura científica para visualizar o progresso da pesquisa.",
        categories: ["Pesquisa"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://litmaps.com",
        icon: "",
        iconFallback: "L",
        themeColor: "bg-purple-600"
    },
    {
        id: "semanticscholar",
        name: "Semantic Scholar",
        company: "Allen Institute for AI",
        description: "Ferramenta de pesquisa gratuita impulsionada por IA para artigos científicos.",
        categories: ["Pesquisa"],
        pricing: ["Uso Gratuito", "Uso por API"],
        url: "https://semanticscholar.org",
        icon: "",
        iconFallback: "S",
        themeColor: "bg-slate-700"
    },
    {
        id: "scite",
        name: "Scite AI",
        company: "Scite",
        description: "Avalia a confiabilidade de citações indicando se apoiam ou contrastam com as afirmações.",
        categories: ["Pesquisa"],
        pricing: ["Uso por Plano"],
        url: "https://scite.ai",
        icon: "",
        iconFallback: "S",
        themeColor: "bg-blue-600"
    },
    {
        id: "grammarly",
        name: "Grammarly",
        company: "Grammarly",
        description: "Correção gramatical avançada e melhoria de estilo de escrita.",
        categories: ["Redação", "Texto"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://grammarly.com",
        icon: "",
        iconFallback: "G",
        themeColor: "bg-green-500"
    },
    {
        id: "languagetool",
        name: "LanguageTool",
        company: "LanguageTool",
        description: "Verificador multilingue de gramática e estilo open-source.",
        categories: ["Redação", "Texto", "Idiomas"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://languagetool.org",
        icon: "",
        iconFallback: "L",
        themeColor: "bg-blue-500"
    },
    {
        id: "writefull",
        name: "Writefull",
        company: "Writefull",
        description: "Assistente de redação focado em publicações acadêmicas.",
        categories: ["Redação", "Pesquisa"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://writefull.com",
        icon: "",
        iconFallback: "W",
        themeColor: "bg-indigo-700"
    },
    {
        id: "trinka",
        name: "Trinka",
        company: "Trinka AI",
        description: "Revisão e correção de gramática projetada para escrita acadêmica e técnica.",
        categories: ["Redação", "Pesquisa"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://trinka.ai",
        icon: "",
        iconFallback: "T",
        themeColor: "bg-sky-500"
    },
    {
        id: "paperpal",
        name: "Paperpal",
        company: "Cactus Communications",
        description: "Revisão de manuscritos usando IA para pesquisadores.",
        categories: ["Redação", "Pesquisa"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://paperpal.com",
        icon: "",
        iconFallback: "P",
        themeColor: "bg-teal-600"
    },
    {
        id: "scispace",
        name: "SciSpace",
        company: "SciSpace",
        description: "Simplifica a formatação e o entendimento de artigos científicos.",
        categories: ["Pesquisa", "Redação"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://scispace.com",
        icon: "",
        iconFallback: "S",
        themeColor: "bg-blue-800"
    },
    {
        id: "wolfram",
        name: "Wolfram Alpha",
        company: "Wolfram Alpha LLC",
        description: "Mecanismo de conhecimento computacional para análise matemática e dados.",
        categories: ["Análise de Dados", "Educação"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://wolframalpha.com",
        icon: "",
        iconFallback: "W",
        themeColor: "bg-red-600"
    },
    {
        id: "orangedatamining",
        name: "Orange Data Mining",
        company: "Bioinformatics Laboratory at the University of Ljubljana",
        description: "Ferramenta visual de mineração de dados e aprendizado de máquina.",
        categories: ["Análise de Dados"],
        pricing: ["Uso Gratuito"],
        url: "https://orangedatamining.com",
        icon: "",
        iconFallback: "O",
        themeColor: "bg-orange-500"
    },
    {
        id: "rapidminer",
        name: "RapidMiner",
        company: "Altair",
        description: "Plataforma de ciência de dados para analistas e equipes empresariais.",
        categories: ["Análise de Dados"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://rapidminer.com",
        icon: "",
        iconFallback: "R",
        themeColor: "bg-orange-600"
    },
    {
        id: "spssmodeler",
        name: "IBM SPSS Modeler",
        company: "IBM",
        description: "Plataforma analítica preditiva de dados da IBM.",
        categories: ["Análise de Dados"],
        pricing: ["Uso por Plano"],
        url: "https://ibm.com/products/spss-modeler",
        icon: "",
        iconFallback: "I",
        themeColor: "bg-blue-700"
    },
    {
        id: "teachermatic",
        name: "Teachermatic",
        company: "Teachermatic",
        description: "Reduz a carga de trabalho de professores gerando planos de aula e recursos.",
        categories: ["Educação", "Gestão Escolar"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://teachermatic.com",
        icon: "",
        iconFallback: "T",
        themeColor: "bg-cyan-600"
    },
    {
        id: "gradescope",
        name: "Gradescope",
        company: "Turnitin",
        description: "Avaliação e correção rápida auxiliada por IA para provas em papel e digitais.",
        categories: ["Gestão Escolar", "Educação"],
        pricing: ["Uso por Plano"],
        url: "https://gradescope.com",
        icon: "",
        iconFallback: "G",
        themeColor: "bg-emerald-500"
    },
    {
        id: "otterai",
        name: "Otter.ai",
        company: "Otter.ai",
        description: "Gravação e transcrição inteligente de reuniões e aulas.",
        categories: ["Gestão Escolar", "Produtividade", "Texto"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://otter.ai",
        icon: "",
        iconFallback: "O",
        themeColor: "bg-blue-500"
    },
    {
        id: "duolingomax",
        name: "Duolingo Max",
        company: "Duolingo",
        description: "Aprenda idiomas de forma eficaz com práticas de conversação impulsionadas por IA.",
        categories: ["Idiomas", "Educação"],
        pricing: ["Uso por Plano"],
        url: "https://duolingo.com",
        icon: "",
        iconFallback: "D",
        themeColor: "bg-green-500"
    },
    {
        id: "elsaspeak",
        name: "Elsa Speak",
        company: "ELSA Corp",
        description: "Coach de pronúncia em inglês baseado em inteligência artificial.",
        categories: ["Idiomas", "Educação", "Áudio"],
        pricing: ["Plano Gratuito", "Uso por Plano"],
        url: "https://elsaspeak.com",
        icon: "",
        iconFallback: "E",
        themeColor: "bg-indigo-600"
    }
];

const categoriesList = ["Todos", "Texto", "Imagens", "Código", "Áudio", "Vídeo", "Educação", "Pesquisa", "Análise de Dados", "Criação Visual", "Redação", "Idiomas", "Gestão Escolar", "Produtividade"];
const pricingList = ["Todos", "Plano Gratuito", "Uso por Plano", "Uso por API", "Uso Gratuito"];
